# Generated by Django 5.2.8 on 2026-04-02 15:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("body", models.TextField()),
                ("summary", models.TextField(blank=True)),
                ("source_url", models.URLField(unique=True)),
                ("external_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ING", "Ingested"),
                            ("SUM", "Summarized"),
                            ("REV", "Pending Review"),
                            ("PUB", "Published"),
                            ("REJ", "Rejected"),
                        ],
                        default="ING",
                        max_length=3,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("originality_score", models.PositiveSmallIntegerField(default=0)),
                ("is_ad_safe", models.BooleanField(default=True)),
                ("language", models.CharField(default="en", max_length=10)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("NEWSAPI", "NewsAPI"),
                            ("GNEWS", "GNews"),
                            ("MEDIASTACK", "MediaStack"),
                            ("TELEGRAM", "Telegram"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("auto_publish", models.BooleanField(default=False)),
                ("trust_score", models.PositiveSmallIntegerField(default=50)),
                ("fetch_interval_minutes", models.PositiveIntegerField(default=60)),
                ("base_url", models.URLField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="auto_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="source_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_posts",
                to="blog.article",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to="blog.newssource",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(fields=["status"], name="blog_articl_status_57fc64_idx"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-fetched_at"], name="blog_articl_fetched_74517e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["source", "status"], name="blog_articl_source__22c096_idx"
            ),
        ),
    ]
