# Generated by Django 5.2.8 on 2026-04-04 08:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_newssource_post_auto_generated_post_summary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="summary_completion_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_estimated_cost_usd",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.000000"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_model",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_prompt_mode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_prompt_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_provider",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="article",
            name="summary_total_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
