# Generated by Django 5.2.8 on 2025-12-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_tag_post_category_comment_post_tags_like"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=255, unique_for_date="publish"),
        ),
    ]
