# Generated by Django 5.2.8 on 2025-12-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="approved",
            field=models.BooleanField(default=True),
        ),
    ]
