# Generated by Django 5.2.8 on 2026-04-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_article_summary_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newssource",
            name="provider",
            field=models.CharField(
                choices=[
                    ("NEWSAPI", "NewsAPI"),
                    ("GNEWS", "GNews"),
                    ("MEDIASTACK", "MediaStack"),
                    ("NEWSDATA", "NewsData"),
                    ("GUARDIAN", "The Guardian"),
                    ("SPACEFLIGHT", "Spaceflight News"),
                    ("OPENLIGADB", "OpenLigaDB"),
                    ("TELEGRAM", "Telegram"),
                    ("CUSTOM", "Custom"),
                ],
                max_length=20,
            ),
        ),
    ]
