from django.urls import path

from api.views import (
    ApiHealthView,
    AuthCsrfAPIView,
    AuthLoginAPIView,
    AuthLogoutAPIView,
    AuthSessionAPIView,
    AnalyticsDashboardAPIView,
    AnalyticsExportCsvAPIView,
    AnalyticsResetAPIView,
    AnalyticsTrendingSnapshotAPIView,
    BookmarkListAPIView,
    CategoryListAPIView,
    CurrentUserAPIView,
    ArticleDetailAPIView,
    ArticleListAPIView,
    ArticleModerationAPIView,
    ArticleQueueAPIView,
    LaunchReadinessAPIView,
    MonitoringHealthAPIView,
    NewsSourceDetailAPIView,
    NewsSourceListAPIView,
    NewsletterDigestTriggerAPIView,
    NewsletterSubscribeAPIView,
    NewsletterSubscriberDetailAPIView,
    NewsletterSubscriberListAPIView,
    NewsletterUnsubscribeAPIView,
    PipelineFetchAPIView,
    PipelinePublishAPIView,
    PipelineRollbackAPIView,
    PipelineRunAPIView,
    PipelineSummarizeAPIView,
    PostBookmarkAPIView,
    PostCommentListCreateAPIView,
    PostLikeAPIView,
    PublishedPostDetailAPIView,
    PublishedPostListAPIView,
    SportsFeedAPIView,
    SportsFixturesAPIView,
    SportsOpenLigaAPIView,
    SportsTablesAPIView,
    TagListAPIView,
)

app_name = "api"

urlpatterns = [
    path("health", ApiHealthView.as_view(), name="health"),
    path("auth/csrf", AuthCsrfAPIView.as_view(), name="auth-csrf"),
    path("auth/login", AuthLoginAPIView.as_view(), name="auth-login"),
    path("auth/logout", AuthLogoutAPIView.as_view(), name="auth-logout"),
    path("auth/session", AuthSessionAPIView.as_view(), name="auth-session"),
    path("users/me", CurrentUserAPIView.as_view(), name="users-me"),
    path("analytics/dashboard", AnalyticsDashboardAPIView.as_view(), name="analytics-dashboard"),
    path("analytics/health", MonitoringHealthAPIView.as_view(), name="analytics-health"),
    path("analytics/launch-readiness", LaunchReadinessAPIView.as_view(), name="analytics-launch-readiness"),
    path("analytics/export.csv", AnalyticsExportCsvAPIView.as_view(), name="analytics-export-csv"),
    path("analytics/trending-snapshot.csv", AnalyticsTrendingSnapshotAPIView.as_view(), name="analytics-trending-snapshot"),
    path("analytics/reset", AnalyticsResetAPIView.as_view(), name="analytics-reset"),
    path("newsletter/subscribe", NewsletterSubscribeAPIView.as_view(), name="newsletter-subscribe"),
    path("newsletter/unsubscribe", NewsletterUnsubscribeAPIView.as_view(), name="newsletter-unsubscribe"),
    path("newsletter/digest/trigger", NewsletterDigestTriggerAPIView.as_view(), name="newsletter-digest-trigger"),
    path("newsletter/subscribers", NewsletterSubscriberListAPIView.as_view(), name="newsletter-subscribers-list"),
    path("newsletter/subscribers/<int:pk>", NewsletterSubscriberDetailAPIView.as_view(), name="newsletter-subscribers-detail"),
    path("sports/feed", SportsFeedAPIView.as_view(), name="sports-feed"),
    path("sports/fixtures", SportsFixturesAPIView.as_view(), name="sports-fixtures"),
    path("sports/tables", SportsTablesAPIView.as_view(), name="sports-tables"),
    path("sports/openliga", SportsOpenLigaAPIView.as_view(), name="sports-openliga"),
    path("news-sources", NewsSourceListAPIView.as_view(), name="news-sources-list"),
    path("news-sources/<int:pk>", NewsSourceDetailAPIView.as_view(), name="news-sources-detail"),
    path("articles", ArticleListAPIView.as_view(), name="articles-list"),
    path("articles/queue", ArticleQueueAPIView.as_view(), name="articles-queue"),
    path("articles/<int:pk>", ArticleDetailAPIView.as_view(), name="articles-detail"),
    path("articles/<int:pk>/<str:action>", ArticleModerationAPIView.as_view(), name="articles-action"),
    path("pipeline/fetch", PipelineFetchAPIView.as_view(), name="pipeline-fetch"),
    path("pipeline/summarize", PipelineSummarizeAPIView.as_view(), name="pipeline-summarize"),
    path("pipeline/publish", PipelinePublishAPIView.as_view(), name="pipeline-publish"),
    path("pipeline/rollback", PipelineRollbackAPIView.as_view(), name="pipeline-rollback"),
    path("pipeline/run", PipelineRunAPIView.as_view(), name="pipeline-run"),
    path("posts", PublishedPostListAPIView.as_view(), name="posts-list"),
    path("posts/<int:pk>", PublishedPostDetailAPIView.as_view(), name="posts-detail"),
    path("posts/<int:pk>/comments", PostCommentListCreateAPIView.as_view(), name="posts-comments"),
    path("posts/<int:pk>/like", PostLikeAPIView.as_view(), name="posts-like"),
    path("posts/<int:pk>/bookmark", PostBookmarkAPIView.as_view(), name="posts-bookmark"),
    path("bookmarks", BookmarkListAPIView.as_view(), name="bookmarks-list"),
    path("categories", CategoryListAPIView.as_view(), name="categories-list"),
    path("tags", TagListAPIView.as_view(), name="tags-list"),
]
